// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94_b0tZzLhHTHowRhxzBZpZgHZk-_-os',
    appId: '1:404684776618:web:49a967b500440ce3a49cd3',
    messagingSenderId: '404684776618',
    projectId: 'cf573-34b16',
    authDomain: 'cf573-34b16.firebaseapp.com',
    storageBucket: 'cf573-34b16.firebasestorage.app',
    measurementId: 'G-T9ZDL07EMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmn7hdhOl7XoJVw8BNV_vE8iFRkJvouI',
    appId: '1:404684776618:android:cd1ca0d3bcc0d868a49cd3',
    messagingSenderId: '404684776618',
    projectId: 'cf573-34b16',
    storageBucket: 'cf573-34b16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_vk5pFz6p-LG2MkkKlEAU5w1NyCfY5Y',
    appId: '1:404684776618:ios:68ae005cefbfaee8a49cd3',
    messagingSenderId: '404684776618',
    projectId: 'cf573-34b16',
    storageBucket: 'cf573-34b16.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_vk5pFz6p-LG2MkkKlEAU5w1NyCfY5Y',
    appId: '1:404684776618:ios:68ae005cefbfaee8a49cd3',
    messagingSenderId: '404684776618',
    projectId: 'cf573-34b16',
    storageBucket: 'cf573-34b16.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA94_b0tZzLhHTHowRhxzBZpZgHZk-_-os',
    appId: '1:404684776618:web:34a48bc9ae2ad63ba49cd3',
    messagingSenderId: '404684776618',
    projectId: 'cf573-34b16',
    authDomain: 'cf573-34b16.firebaseapp.com',
    storageBucket: 'cf573-34b16.firebasestorage.app',
    measurementId: 'G-43XY8T7G58',
  );
}